### ISSUE TITLE
test環境のDBを使用する方法

### ISSUE THREAD

**Issue by ha-matsumu** [ha-matsumu/todo-with-express-and-mysql#9]
**参考資料**
https://github.com/ha-matsumu/todo-with-express-and-mysql/pull/8#issuecomment-456365219
https://github.com/sequelize/cli/issues/413
https://programmagick.com/blog?slug=node_jest_sequelize_testing

**Comment by ha-matsumu** [comment]
1. test用のデータベース作成
`env NODE_ENV=test node_modules/.bin/sequelize db:create`

1. マイグレーションを実行して、Todosテーブルを作成
`env NODE_ENV=test node_modules/.bin/sequelize db:migrate`

**Comment by ha-matsumu** [comment]
`npm test`を実行したときにテスト環境のDBをしようするようにする。
→`package.json`のscriptsのtestに`env NODE_ENV=test`を追加する。
```
"scripts": {
    "test": "env NODE_ENV=test mocha"
  },
```

**Comment by tsuyopon-xyz** [comment]
https://github.com/ha-matsumu/todo-with-express-and-mysql/issues/9#issuecomment-456427210
↑

僕がNODE_ENVをscriptsにセットするときは

```json
"scripts": {
    "test": "env NODE_ENV=test mocha"
},
```

ではなく、

```json
"scripts": {
    "test": "NODE_ENV=test mocha"
},
```

のように `env` をセットしなくても動いていたような気がしたので、 `env` を付けない場合は正しく動かないでしょうか？
(現状正しく動いていれば修正の必要はなく、単純に僕が `env` を使ったことがなく気になったので質問しました。)

---
FYI

もう既に理解されているかもですが、

`NODE_ENV=〇〇` のように、環境変数はprocess.env.環境変数名で環境変数の値を取得することができます^^

今回の場合だとNODE_ENVが環境変数名になるので `process.env.NODE_ENV` に NODE_ENV環境変数にセットした値が入るようになります。

https://github.com/ha-matsumu/todo-with-express-and-mysql/blob/feature/part4/src/models/index.js#L7

**Comment by ha-matsumu** [comment]
> env を付けない場合は正しく動かないでしょうか？
`env`付けても付けなくて正しく動作しました！
